pub const MAX_ERROR_BODY_BYTES: usize = 16_384;
pub const MAX_STREAM_PREFETCH_FRAMES: usize = 5;
pub const MAX_STREAM_PREFETCH_BYTES: usize = 16_384;
pub const MAX_STREAM_PREFETCH_OVERFLOW_BYTES: usize = 1024 * 1024;
