name: probe3-no-token-base
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust || 'true' }}
      data: ${{ steps.filter.outputs.data || 'true' }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        if: github.event_name == 'pull_request'
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        if: github.event_name == 'pull_request'
        with:
          filters: |
            rust:
              - 'crates/**'
